# Generated by Django 5.0.7 on 2024-12-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initialtest',
            options={'ordering': ['difficulty', 'id']},
        ),
        migrations.RenameField(
            model_name='initialtest',
            old_name='options',
            new_name='test_cases',
        ),
        migrations.RemoveField(
            model_name='initialtest',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='initialtest',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1),
        ),
        migrations.AlterField(
            model_name='initialtest',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
