# Generated by Django 5.0.7 on 2024-12-16 13:36

import Coding.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0003_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['difficulty', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='problem',
            name='domain',
            field=models.ForeignKey(default=Coding.models.Domain.get_default_domain, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='Coding.domain'),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_template',
            field=models.TextField(default='def solution():\n    pass'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10),
        ),
    ]
