# Generated by Django 5.1.4 on 2024-12-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0004_alter_problem_options_remove_problem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='has_completed_initial_test',
            field=models.BooleanField(default=False),
        ),
    ]
