# Generated by Django 5.1.4 on 2024-12-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0005_membre_has_completed_initial_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='penalty_points',
            field=models.IntegerField(default=5, help_text='Points deducted if time limit exceeded'),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=300, help_text='Time limit in seconds'),
        ),
    ]
